"""initial schema

Revision ID: dcb4f29ef0be
Revises: 
Create Date: 2026-08-01 11:37:50.667713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dcb4f29ef0be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrier',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('contact_person', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('contact_person', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('can_see_money', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('manager','owner','accountant')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('container',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ref_no', sa.String(length=32), nullable=False),
    sa.Column('container_no', sa.String(length=20), nullable=True),
    sa.Column('container_type', sa.String(length=16), nullable=True),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=True),
    sa.Column('is_consolidated', sa.Boolean(), nullable=False),
    sa.Column('origin_location', sa.String(length=80), nullable=False),
    sa.Column('dest_location', sa.String(length=80), nullable=False),
    sa.Column('current_stage_code', sa.String(length=40), nullable=False),
    sa.Column('current_stage_since', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("container_type IS NULL OR container_type IN ('20DC','40DC','40HC','REEFER','OT','TANK')", name='ck_container_type'),
    sa.CheckConstraint("direction IN ('ge_uz','uz_ge')", name='ck_container_direction'),
    sa.CheckConstraint("status IN ('active','delivered','cancelled','archived')", name='ck_container_status'),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref_no')
    )
    op.create_table('leg',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('container_id', sa.BigInteger(), nullable=False),
    sa.Column('seq', sa.SmallInteger(), nullable=False),
    sa.Column('transport_type', sa.String(length=16), nullable=False),
    sa.Column('from_location', sa.String(length=80), nullable=False),
    sa.Column('to_location', sa.String(length=80), nullable=False),
    sa.Column('carrier_id', sa.BigInteger(), nullable=True),
    sa.Column('planned_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("transport_type IN ('rail','sea_ferry','truck','other')", name='ck_leg_transport'),
    sa.CheckConstraint('seq > 0', name='ck_leg_seq_positive'),
    sa.ForeignKeyConstraint(['carrier_id'], ['carrier.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['container_id'], ['container.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('container_id', 'seq', name='uq_leg_container_seq')
    )
    op.create_table('stage_event',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('container_id', sa.BigInteger(), nullable=False),
    sa.Column('stage_code', sa.String(length=40), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('changed_by', sa.BigInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['container_id'], ['container.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_event_container_id'), 'stage_event', ['container_id'], unique=False)
    op.create_table('charge_line',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('container_id', sa.BigInteger(), nullable=False),
    sa.Column('leg_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('charge_type', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('rate_to_usd', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=14, scale=2), sa.Computed('amount * rate_to_usd', persisted=True), nullable=False),
    sa.Column('is_estimated', sa.Boolean(), nullable=False),
    sa.Column('payment_status', sa.String(length=8), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("charge_type IN ('freight_rail','ferry','truck','customs','demurrage','detention','storage','forwarding','insurance','terminal_handling','other')", name='ck_charge_type'),
    sa.CheckConstraint("currency IN ('USD','EUR','GEL','AZN','TMT','UZS','RUB')", name='ck_charge_currency'),
    sa.CheckConstraint("kind IN ('income','expense')", name='ck_charge_kind'),
    sa.CheckConstraint("payment_status IN ('unpaid','partial','paid')", name='ck_charge_paystatus'),
    sa.CheckConstraint('amount > 0', name='ck_charge_amount_positive'),
    sa.CheckConstraint('paid_amount >= 0 AND paid_amount <= amount', name='ck_charge_paid_range'),
    sa.CheckConstraint('rate_to_usd > 0', name='ck_charge_rate_positive'),
    sa.ForeignKeyConstraint(['container_id'], ['container.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['leg_id'], ['leg.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charge_line_container_id'), 'charge_line', ['container_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_charge_line_container_id'), table_name='charge_line')
    op.drop_table('charge_line')
    op.drop_index(op.f('ix_stage_event_container_id'), table_name='stage_event')
    op.drop_table('stage_event')
    op.drop_table('leg')
    op.drop_table('container')
    op.drop_table('users')
    op.drop_table('client')
    op.drop_table('carrier')
    # ### end Alembic commands ###
